image: node:9.11.2

stages:
  - test
  - deploy

Lint:
  before_script:
    - npm install --progress=false
  stage: test
  script: npm run lint

Posttest:
  stage: test
  allow_failure: true
  before_script:
    - npm install --progress=false
    - npm i -g nsp
  script : npm start && nsp run check

build_img:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    LATEST_TAG: $CI_REGISTRY_IMAGE:lts
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -t $LATEST_TAG .
    - docker push $IMAGE_TAG
    - docker push $LATEST_TAG
  only:
    - tags
