Build:
  stage: build
  before_script: 
    - apt update 
    - apt  install -y tzdata && dpkg-reconfigure -f noninteractive tzdata 
    - apt install npm -y && npm i
  script: npm build
Test: 
  stage: test
  script: npm run posttest
